#!/bin/sh

echo ".bashrc:"
diff ~/.bashrc ~/git/configs/.bashrc
echo ".emacs:"
diff ~/.emacs ~/git/configs/.emacs
echo ".fvwm2rc:"
diff ~/.fvwm/.fvwm2rc ~/git/configs/.fvwm2rc
echo ".gvimrc:"
diff ~/.gvimrc ~/git/configs/.gvimrc
echo ".irssi/config:"
diff ~/.irssi/config ~/git/configs/.irssi/config
echo ".mpdconf:"
diff ~/.mpdconf ~/git/configs/.mpdconf
echo ".ncmpcpp/config:"
diff ~/.ncmpcpp/config ~/git/configs/.ncmpcpp/config
echo ".pentadactylrc:"
diff ~/.pentadactylrc ~/git/configs/.pentadactylrc
echo ".ratpoisonrc:"
diff ~/.ratpoisonrc ~/git/configs/.ratpoisonrc
echo ".screenrc:"
diff ~/.screenrc ~/git/configs/.screenrc
echo ".vimrc:"
diff ~/.vimrc ~/git/configs/.vimrc
echo ".Xdefaults:"
diff ~/.Xdefaults ~/git/configs/.Xdefaults
echo ".xinitrc:"
diff ~/.xinitrc ~/git/configs/.xinitrc
